# Generated by Django 2.2 on 2018-11-16 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('documento', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('cuit', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pasaje',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('fecha_emision', models.DateTimeField()),
                ('origen', models.CharField(max_length=200)),
                ('destino', models.CharField(max_length=200)),
                ('id_agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasajes.Agente')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasajes.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('documento', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateTimeField()),
                ('id_agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasajes.Agente')),
                ('id_localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasajes.Localidad')),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='id_localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasajes.Localidad'),
        ),
        migrations.AddField(
            model_name='agente',
            name='id_localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasajes.Localidad'),
        ),
    ]
