# Generated by Django 2.2 on 2018-11-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasajes', '0002_auto_20181120_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agente',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='familiar',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pasaje',
            name='fecha_emision',
            field=models.DateField(),
        ),
    ]
