# Generated by Django 2.2 on 2018-12-03 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pasajes', '0003_auto_20181120_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pasaje',
            old_name='fecha_emision',
            new_name='fecha_viaje',
        ),
        migrations.AlterField(
            model_name='agente',
            name='id_localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasajes.Localidad', verbose_name='Localidad'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='id_localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasajes.Localidad', verbose_name='Localidad'),
        ),
        migrations.AlterField(
            model_name='familiar',
            name='id_agente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasajes.Agente', verbose_name='Agente'),
        ),
        migrations.AlterField(
            model_name='familiar',
            name='id_localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasajes.Localidad', verbose_name='Localidad'),
        ),
        migrations.AlterField(
            model_name='pasaje',
            name='id_agente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasajes.Agente', verbose_name='Agente'),
        ),
        migrations.AlterField(
            model_name='pasaje',
            name='id_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasajes.Empresa', verbose_name='Empresa'),
        ),
    ]
