# Generated by Django 2.2 on 2018-12-03 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasajes', '0004_auto_20181203_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasaje',
            name='fecha_emision',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 3, 14, 36, 13, 784548)),
        ),
    ]
