# Generated by Django 2.2 on 2018-12-04 12:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pasajes', '0005_pasaje_fecha_emision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasaje',
            name='fecha_emision',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 4, 12, 24, 53, 1522, tzinfo=utc)),
        ),
    ]
