# Generated by Django 2.2 on 2018-12-10 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasajes', '0006_auto_20181204_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasaje',
            name='via',
            field=models.CharField(default='Terrestre', max_length=200),
        ),
        migrations.AlterField(
            model_name='pasaje',
            name='fecha_emision',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 10, 41, 1, 650391)),
        ),
    ]
