# Generated by Django 2.2 on 2018-12-10 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasajes', '0007_auto_20181210_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasaje',
            name='fecha_emision',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 10, 42, 23, 409435)),
        ),
        migrations.AlterField(
            model_name='pasaje',
            name='via',
            field=models.CharField(max_length=200),
        ),
    ]
