# Generated by Django 2.2 on 2018-12-14 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasajes', '0008_auto_20181210_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasaje',
            name='fecha_emision',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 14, 8, 47, 59, 494458)),
        ),
        migrations.AlterField(
            model_name='pasaje',
            name='fecha_viaje',
            field=models.DateField(null=True),
        ),
    ]
