# Generated by Django 2.2 on 2018-12-14 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasajes', '0009_auto_20181214_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasaje',
            name='fecha_emision',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 14, 8, 49, 21, 985279)),
        ),
        migrations.AlterField(
            model_name='pasaje',
            name='fecha_viaje',
            field=models.DateField(),
        ),
    ]
