# Generated by Django 2.1.3 on 2018-12-15 22:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasajes', '0010_auto_20181214_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasaje',
            name='fecha_emision',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 15, 19, 29, 44, 712410)),
        ),
    ]
