# Generated by Django 2.2 on 2018-12-17 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasajes', '0011_auto_20181217_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasaje',
            name='fecha_emision',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 17, 10, 19, 43, 129931)),
        ),
    ]
