# Generated by Django 2.2 on 2018-12-17 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasajes', '0012_auto_20181217_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasaje',
            name='fecha_emision',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 17, 10, 30, 25, 959443)),
        ),
    ]
