# Generated by Django 2.1.3 on 2018-12-22 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pasajes', '0013_auto_20181217_1330'),
        ('pasajes', '0011_auto_20181215_2229'),
    ]

    operations = [
    ]
